config/routes.rb
Rails.application.routes.draw do
  get '/login',          to: 'sessions#new'
  post '/login',         to: 'sessions#create'
  delete '/logout',      to: 'sessions#destroy'


  scope :users do
    get '/:id/plays', to: 'users#plays', as: 'user_plays'
    patch '/:id/email', to: 'users#update_email', as: 'update_user_email'
    patch '/:id/password', to: 'users#update_password', as: 'update_user_password'
  end

  resources :users, only: [:edit]
  resources :username_recovery, only: [:new, :create]
  resources :password_resets,   only: [:new, :create, :edit, :update]

  post '/viewings/:id', to: 'viewings#update_user', as: 'update_user_viewings'

  root 'sessions#new'
end

app/models/theater.rb
class Theater < ApplicationRecord
  validates :name, presence: true, uniqueness: true, length: { maximum: 255 }
  has_many :plays, dependent: :destroy

  # Returns a list of the theater's plays for the current voting period
  def current_voting_period_plays
    plays.for_current_voting_period
  end
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :remember_token, :reset_token
  extend Auth
  include UserSession, PasswordReset, UserViewings
  has_many :viewings, dependent: :destroy
  has_many :nominations, dependent: :destroy
  before_save { email.downcase! }
  validates :username,  presence: true, length: { maximum: 50 },
                        uniqueness: true
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email,     presence: true, length: { maximum: 255 },
                        format: { with: VALID_EMAIL_REGEX }
  validates :full_name, presence: true, length: { maximum: 50 }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, :if => :password
  validates :admin, inclusion: { in: [true, false] }
  validates :membership_active, inclusion: { in: [true, false] }

  private
end

app/controllers/admin/users_controller.rb
module Admin
  class UsersController < Admin::ApplicationController
    def export
        @users = User.all

        respond_to do |format|
            format.html
            format.csv { send_data @users.to_csv }
        end
    end

    # To customize the behavior of this controller,
    # simply overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = User.all.paginate(10, params[:page])
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   User.find_by!(slug: param)
    # end

    # See https://administrate-docs.herokuapp.com/customizing_controller_actions
    # for more information







  end
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  def new
    super
  end

  # POST /resource/password
  def create
    super
  end

  # GET /resource/password/edit?reset_password_token=abcdef
  def edit
    super
  end

  # PUT /resource/password
  def update
    super
  end

  protected

  def after_resetting_password_path_for(resource)
    super(resource)
  end

  # The path used after sending reset password instructions
  def after_sending_reset_password_instructions_path_for(resource_name)
    super(resource_name)
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
# before_filter :configure_sign_up_params, only: [:create]
# before_filter :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.for(:sign_up) << :attribute
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.for(:account_update) << :attribute
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
# before_filter :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.for(:sign_in) << :attribute
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :correct_user?

  def plays
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update_email
    @user = User.find(params[:id])
    if @user.update_attributes(email)
      flash[:success] = "Email successfully updated"
      redirect_to user_plays_path(@user)
    else
      render 'edit'
    end
  end

  def update_password
    @user = User.find(params[:id])
    if @user.update_attributes(password)
      flash[:success] = "Password successfully updated"
      redirect_to user_plays_path(@user)
    else
      render 'edit'
    end
  end

  private

    def password
      params.require(:user).permit(:password, :password_confirmation)
    end

    def email
      params.require(:user).permit(:email)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<% if @user.errors.any? %>
  <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

<h1>Update your email</h1>

<%= form_for(@user, url: update_user_email_path(@user)) do |f| %>
  <%= f.label :email %>
  <%= f.email_field :email %>

  <%= f.submit "Update email" %>
<% end %>

<h1>Update your password</h1>

<%= form_for(@user, url: update_user_password_path(@user)) do |f| %>
  <%= f.label :password %>
  <%= f.password_field :password %>

  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>

  <%= f.submit "Update password" %>
<% end %>

app/views/users/home.html.erb
<html>
<head>
    <title>User Dashboard</title>
</head>
<body>
  <div class="clear title">
    <div class="col-12 title-box">
      <h2>Show Attendance <%= Time.now.strftime("%Y") %></h2>
    </div>
  </div>

  <div class="clear content">
    <div class="col-12 content-box">

      <%= form_for current_user, url: user_viewings_path do |f| %>
        <% @theaters.each do |theater| %>
          <h3><%= theater.name %></h3>
          <div style="padding-bottom: 10px; margin-bottom: 20px; border-bottom: 1px solid #eee;">
            <% theater.plays_for_current_voting_period.each do |p| %>
              <p>
                <label>
                  <%= f.check_box :viewings, {name: "user[viewings][]", id: nil, checked: current_user.has_viewed?(p)}, p.id, nil %>
                  <strong><%= p.title %></strong>
                </label>
              </p>
            <% end %>
          </div>
        <% end %>

        <%= f.submit "SUBMIT", class: "form-submit-button" %>
      <% end %>

    </div>
  </div>

</body>
</html>

app/views/users/index.html.erb
This is the dashboard for a user!

Let's get some data on here!

Data that we may want on this page:

1) All Plays
2) Nomiation form
3) All nominations that a particular user has submitted
4) All votes that a particular user has submitted
5) ALl plays a user has seen (viewings)
6) All plays a user can select form
7) Area to add more possible plays/theaters for viewings

app/views/users/plays.html.erb
<h1>Dashboard</h1>

<%= form_tag update_user_viewings_path(@user), action: :post do %>
  <% Theater.all.each do |theater| %>
    <h2><%= theater.name %></h2>
    <% theater.current_voting_period_plays.each do |play| %>
      <ul>
        <% if @user.has_viewed? play %>
          <li>
            <%= check_box_tag 'play_ids[]', play.id, true %>
            <%= play.title %>
          </li>
        <% else %>
        <li>
          <%= check_box_tag 'play_ids[]', play.id %>
          <%= play.title %>
        </li>
        <% end %>
      </ul>
    <% end %>
  <% end %>
  <%= submit_tag("Submit") %>
<% end %>

app/views/users/settings_page.html.erb
<h1>Update Your Settings</h1>

<strong>Update your information:</strong><br><br>
<%= form_tag("/users/change_settings", method: "post") do %>

  Full name: <input type="text" name="full_name" value="<%= current_user.full_name%>"><br>
  <br>

  Username: <input type="text" name="username" value="<%= current_user.username %>"><br>
  <br>

  Email: <input type="text" name="email" value="<%= current_user.email %>"><br>
  <br>

  <%= submit_tag("Save") %>
<% end %>

<br>

<strong>Change your password:</strong><br><br>
<%= form_tag("/users/change_password", method: "post") do %>

  New Password: <input type="password" name="password"><br>
  <br>

  Confirm Password: <input type="password" name="confirm_password"><br>
  <br>

  <%= submit_tag("Save") %>
<% end %>